export const passwordRequired = (v) => !!v || "Password required"
export const passwordConfirmed = (v, password) => v === password || "Passwords must match"
export const emailRequired = (v) => !!v || "Email required"
export const emailValid = (v) => /.+@.+\..+/.test(v) || "Invalid email"
export const usernameRequired = (v) => !!v || "Username required"
export const mustBeOver18 = (v) => v === true || "Must be over 18 years old"
export const termsAccepted = (v) => v === true || "Must accept the terms"
export const termSectionRequired = (v) => !!v || "Section required"
export const termParagraphRequired = (v) => !!v || "Paragraph required"
export const termContentRequired = (v) => !!v || "Content required"
